# Generated by Django 2.2.7 on 2019-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_body', models.TextField(default='')),
                ('req_type', models.TextField()),
                ('req_from', models.TextField()),
                ('resp_status', models.TextField()),
                ('resp_body', models.TextField(default='')),
                ('req_date', models.TextField()),
                ('resp_date', models.TextField()),
            ],
        ),
    ]
