# Generated by Django 2.2.7 on 2019-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id_sneaker', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=45)),
                ('material', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
