# Generated by Django 2.2.7 on 2019-11-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
        ('sneakers', '0001_initial'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakersColorsSizesRel',
            fields=[
                ('id_relation', models.AutoField(primary_key=True, serialize=False)),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.Colors')),
                ('id_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizes.Sizes')),
                ('id_sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.Sneakers')),
            ],
        ),
    ]
