# Generated by Django 2.2.7 on 2019-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_auto_20191109_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='price_coef',
            field=models.FloatField(null=True),
        ),
    ]
