# Generated by Django 2.2.7 on 2019-11-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_auto_20191109_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='price_coef',
            field=models.FloatField(default=None, null=True),
        ),
    ]
