# Generated by Django 2.2.7 on 2019-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='price_coef',
            field=models.FloatField(default=None, null=True),
        ),
    ]
